### ISSUE TITLE
Update Supported Methods List

### ISSUE THREAD

**Issue by dehlen** [impronunciable/moviedb#26]
Please add all supported methods of this library to the list in the README file. 
For example the method ``` searchTv()``` is supported but not listed.

Best Regards,
David

**Comment by impronunciable** [comment]
I can do it. A pull request will be appreciated too.

**Comment by dehlen** [comment]
It seems that there are too many methods which would expand the list in the README file too much.
I guess there has to be another solution to present the possible methods which one can call.
Maybe an article in the Wiki.

**Comment by impronunciable** [comment]
It can be. I'll take a look at the weekend.

**Comment by impronunciable** [comment]
@dehlen Thanks for reporting and sorry for the REALLY late response. I created this wiki page https://github.com/impronunciable/moviedb/wiki/Library-endpoints

and also a script for autogenerating the table https://github.com/impronunciable/moviedb/blob/master/tools/towiki.js

I'll add it as a postpublish script or something in the future.

Thanks for reporting.
