### ISSUE TITLE
requestToken

### ISSUE THREAD

**Issue by andreme** [impronunciable/moviedb#30]
Hi,

I'm wondering why requestToken is called before a request? It doesn't seem to be used and when many requests are start it doubles the call count to TMDB which is a problem due to their rate limiting?

I commented the code out and could run my queries without a problem.

Thanks
Andre

**Comment by impronunciable** [comment]
It fetches a request token only if you don't have one or it is expired, so it only add one request the first time you call the API, it's very handy not to worry about the requestToken if the lib can do it for you. It can be an option, proposals are well received :)

**Comment by andreme** [comment]
It does start multiple requests if you don't wait for the first to finish :)
So it's for external usage?
I'll probably just set a dummy token that never expires to easily solve my problem.
