### ISSUE TITLE
Experiencing duplicated requests per query.

### ISSUE THREAD

**Issue by AlonMiz** [impronunciable/moviedb#41]
Getting error `"status_code":25`, although never asking 40 requests.
`text: '{"status_code":25,"status_message":"Your request count (43) is over the allowed limit of 40."}\n',
`
My suspicion is that every query creating double requests, resulting in `"over the allowed limit"` requests.
When i am requesting 22 single queries it shows 4 errors (generating actually 44 requests).
Indicating my Thesis is probably true.

**Comment by impronunciable** [comment]
I'll take a look now, thanks for reporting

**Comment by impronunciable** [comment]
@AlonMiz are you doing the requests in parallel? I think what is happening is that you are performing all the requests at the same time and the library is then doing one requestToken call per each call. Can you try first calling `requestToken` and then doing all the other calls?

you can do

```
mdb.requestToken(function(){
  // your other requests
})
```

Let me know if that helps.
