### ISSUE TITLE
how to get data for page 2 or more

### ISSUE THREAD

**Issue by rishabh1403** [impronunciable/moviedb#44]
when ever i call 
`mdb.miscUpcomingMovies(function (err, result) { })`
the result always shows only resluts from page one , how to get results from later pages ?
Thanks

**Comment by impronunciable** [comment]
Hi @rishabh1403,

The library endpoints accepts a first parameter as an object with query parsmeters. In your case, for getting for example the second page you can do

```
mdb.miscUpcomingMovies((page: 2}, function (err, result) { })
```

**Comment by rishabh1403** [comment]
Hello @impronunciable ,
Thanks That helped !!
