### ISSUE TITLE
Support for append_to_response param

### ISSUE THREAD

**Issue by nunof07** [impronunciable/moviedb#45]
Some methods in the TMDb API have the `append_to_response` param that allows requesting additional information.

For example: `/movie/id` requests the movie's info and `/movie/id?append_to_response=videos` requests both the movie's info and its videos in the same request, avoiding making two separate requests for this.

It would be nice if this library would be able to support this too.

**Comment by impronunciable** [comment]
This is interesting. I think you cam pass that parameter inside the first parameter on the call. For example for move info you can do
```
mdb.movieInfo({append_to_response: 'videos', id: 11}, function(err, res){})
```

and should work. Are you thinking about something different?

**Comment by nunof07** [comment]
That's exactly what I was looking for. Didn't know that was possible.

Thanks!

**Comment by m3hari** [comment]
how to append multiple things?  for instance how can I  do append_to_response videos and credits
