### ISSUE TITLE
Missing function in npm release (movieReleaseDates)

### ISSUE THREAD

**Issue by orecus** [impronunciable/moviedb#50]
Hi,

Seems like "mdb.movieReleaseDates" is not present in the release that is available on npm, I get the following error when i try to use it.

`
[TypeError: mdb.movieReleaseDates is not a function]
`

Any chance to get a new version published to npm, seems to be implemented (or started) here on github?

**Comment by impronunciable** [comment]
@orecus done. Thanks for reporting and let me know if you still find issues with version 0.2.4

**Comment by orecus** [comment]
Awesome. I'll give it a whirl tomorrow and update if I discover any issues!

Thanks for the super suick turnaround! :)
