### ISSUE TITLE
Watchlist endpoints have changed

### ISSUE THREAD

**Issue by grantholle** [impronunciable/moviedb#52]
According to the [docs](https://developers.themoviedb.org/3/account/7bS3fEzCaxB938c84), the endpoints for TV (currently not available as a method) and Movie watchlists should be `/account/{account_id}/watchlist/movies` and `/account/{account_id}/watchlist/tv`.

Also, the endpoint to update watchlists has changed to `/account/{account_id}/watchlist`.

**Comment by impronunciable** [comment]
@grantholle Thanks Grant, I'll take a look
