### ISSUE TITLE
TV changes?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [impronunciable/moviedb#54]
I see movieChanges, but where are tvChanges?

**Comment by GeoffreyPlitt** [comment]
Sorry, I meant where are miscChangedTV

**Comment by impronunciable** [comment]
@GeoffreyPlitt just added it. It's available on npm (v 0.2.6) thanks for reporting!

**Comment by GeoffreyPlitt** [comment]
Great, thanks!

**Comment by GeoffreyPlitt** [comment]
I don't see it on https://github.com/impronunciable/moviedb/wiki/Library-endpoints, and I just tested it out, miscChangedTV does not exist?

**Comment by GeoffreyPlitt** [comment]
@impronunciable ?

**Comment by impronunciable** [comment]
Sorry, I forget to update it in the wiki. It's https://github.com/impronunciable/moviedb/blob/master/lib/endpoints.json#L112

**Comment by impronunciable** [comment]
added to the wiki @GeoffreyPlitt

**Comment by GeoffreyPlitt** [comment]
Perfect, thanks!
