### ISSUE TITLE
Please include TV Seasons -> Get Videos

### ISSUE THREAD

**Issue by bboh** [impronunciable/moviedb#55]
Hi,

I noticed today that  https://developers.themoviedb.org/3/tv-seasons/get-tv-season-videos seems to be missing. If possible please include the method.

thanks in advance.

**Comment by impronunciable** [comment]
Cool, I'll try to do it today

**Comment by impronunciable** [comment]
@bboh added and published new version (0.2.7) on npm. Let me know if it doesn't work for you

**Comment by impronunciable** [comment]
the method is called `tvSeasonVideos`
