### ISSUE TITLE
Enable Travis CI tests

### ISSUE THREAD

**Issue by amilajack** [impronunciable/moviedb#60]
<img width="125" alt="screen shot 2016-11-11 at 9 37 29 am" src="https://cloud.githubusercontent.com/assets/6374832/20224263/7f931f5a-a7f2-11e6-8a74-eaaf61e376e8.png">

Seems like travis ci tests haven't been enabled yet. This can be done at https://travis-ci.org. CI is really helpful when making PR's.

**Comment by impronunciable** [comment]
enabled it, i'll see if it works and close if it's the case

**Comment by amilajack** [comment]
<img width="948" alt="screen shot 2016-11-11 at 9 44 02 am" src="https://cloud.githubusercontent.com/assets/6374832/20224453/65302f9e-a7f3-11e6-9005-bc143a0d0e75.png">
