### ISSUE TITLE
genreList is not a function

### ISSUE THREAD

**Issue by rokit** [impronunciable/moviedb#67]
When I run this code:

```
    mdb.genreList((err, res) => {
      console.log(res);
    });
```
I get "genreList is not a function." The other examples use a query, ie:

```
mdb.searchMovie({ query: 'Alien' }, (err, res) => {
  console.log(res);
});
```
Of course, genreList doesn't need a query, so not sure if I'm doing it wrong or if it's a bug.

**Comment by impronunciable** [comment]
@rokit Hi, the issue is `genreList` is not an endpoint. I think you are looking for one of these:

- `genreMovieList` 
- `genreTvList`
- `genreMovies`

https://github.com/impronunciable/moviedb/blob/master/lib/endpoints.json#L83

**Comment by rokit** [comment]
I see, thanks. I was getting my info from the wiki, which seems to be out of date. `genreList` is listed as an endpoint, and `genreMovieList` and `genreTvList` are not.

**Comment by katekozlova** [comment]
Hi, please update the documentation. It is really confused. Thanks!
https://github.com/impronunciable/moviedb/wiki/Library-endpoints
