### ISSUE TITLE
Find Person, beginning at Movie

### ISSUE THREAD

**Issue by thomax** [impronunciable/moviedb#68]
Given a list of movies, I'm trying to find which persons constitute a crew and a cast.

Currently, I'm fetching movies by genre. Then fetching credits for each movieId. This gives me cast and crew for each movie. However, I can't seem to find a way to get person from credit. Is this possible?

**Comment by impronunciable** [comment]
@thomax I think this is a question for TheMovieDB more than this library. I can't help with this but check here https://www.themoviedb.org/faq/general

**Comment by thomax** [comment]
Sorry if I'm not getting this... According to https://developers.themoviedb.org/3/credits there exists an endpoint for fetching credit by id, and the response includes person id. However, there is no matching method in the moviedb api for reaching through to that endpoint (https://github.com/impronunciable/moviedb/wiki/Library-endpoints). Or have I misunderstood something?

**Comment by thomax** [comment]
Maybe this will do the trick? https://github.com/impronunciable/moviedb/pull/69

Also, there seems to be a bug in the `credit/:id`endpoint at themoviedb.org. I've filed a bug report over here https://www.themoviedb.org/talk/5881ff51c3a368146700c509
