### ISSUE TITLE
TV changes for a specific ID?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [impronunciable/moviedb#84]
Hi,

I'm looking for the following API call: ```tv/:id/changes```.

I don't see it mentioned on https://github.com/impronunciable/moviedb/wiki/Library-endpoints .

Can we get that added?

**Comment by impronunciable** [comment]
Just added it to version 0.2.9
let me know if it doesn't work

**Comment by GeoffreyPlitt** [comment]
Thanks!
