### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by yousefamar** [impronunciable/moviedb#92]
It seems like even small maintenance, like accepting PRs for security updates, has been on ice for years now. Are you still maintaining this repo? I think it would be a shame to let it die and/or splinter into a million forks, especially since [the only other Node.js wrapper linked in the API docs](https://github.com/raqqa/node-tmdb/) is even more dead.

If you're no longer interested in maintaining this project, I would gladly offer to do so for you, here and on npm.

**Comment by rontav** [comment]
We continued to improve on @impronunciable initial work over on [moviedb-promise](https://github.com/grantholle/moviedb-promise). Usually, @grantholle is very quick to respond to issues and PRs.

It would be awesome if someone took over maintaining the moviedb package so that we won't have multiple similar packages/repos for the same API.

**Comment by impronunciable** [comment]
Hi @yousefamar thank you for the offer. I added you as mantainer :) let me know if you have any questions and feel free to continue working on it.

**Comment by impronunciable** [comment]
@rontav Is it also great to know you used this code an improved it 👍

**Comment by grantholle** [comment]
@yousefamar You're welcome to contribute on the [moviedb-promise](https://github.com/grantholle/moviedb-promise) package. I recently ported it to TypeScript and think it would be really cool to be able to add types for the different requests and responses, but would require a lot of manual labor. Their docs have all of that info so it's just a matter of copying and pasting.

@impronunciable I also think it would be cool to merge the two projects, although I don't know the logistics of how that would go down. I try to stay on top of issues and PR's

**Comment by impronunciable** [comment]
@grantholle didn't know about your package. I'm glad you worked on it. Since I'm not actively working on this I'd accept a PR with a deprecation notice and a link to your repo :)
